=== mcm104/uw-capstone-fort-steilacoom/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">

    <xs:element name="newsletterIndex">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="terms">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="term" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="preferredTerm"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="alternateTerm"/>
                                        <xs:element minOccurs="0" name="parentTerm">
                                            <xs:complexType>
                                                <xs:attribute ref="term"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="childTerm">
                                            <xs:complexType>
                                                <xs:attribute ref="term"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="relatedTerm">
                                            <xs:complexType>
                                                <xs:attribute ref="term"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="scopeNotes"/>
                                        <xs:element minOccurs="0" name="definition"/>
                                        <xs:element minOccurs="0" name="sources">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="source">
                                                  <xs:complexType>
                                                  <xs:attribute ref="uri"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="term" type="xs:IDREF"/>
    <xs:attribute name="uri" type="xs:anyURI"/>
</xs:schema>

=== mcm104/uw-capstone-fort-steilacoom/index_blankXMLfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<newsletterIndex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="index.xsd">
    <terms>
        <term id=""> <!-- 1...* --> <!-- id (xs:ID) required -->
            <preferredTerm></preferredTerm> <!-- 1...1 -->
            <alternateTerm></alternateTerm> <!-- 0...* -->
            <parentTerm term_id=""/> <!-- 0...1 --> <!-- term_id (xs:IDREF) required -->
            <relatedTerm term_id=""/> <!-- 0...* --> <!-- term_id (xs:IDREF) required -->
            <scopeNotes></scopeNotes> <!-- 0...1 -->
            <definition></definition> <!-- 0...1 -->
            <sources> <!-- 0...1 -->
                <source uri=""/> <!-- 1...* --> <!-- uri (xs:anyURI) required -->
            </sources>
        </term>
    </terms>
</newsletterIndex>

=== mcm104/uw-capstone-fort-steilacoom/delete/index_xmltestingDemo.xml
<newsletterIndex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="index.xsd">
	<terms>
		<!-- <terms>
		<term id='term_'>
		<preferredTerm></preferredTerm>
		<alternateTerm/>
		<parentTerm term_id=''></parentTerm>
		<relatedTerm term_id=''></relatedTerm>
		<scopeNotes/>
		<definition/>
		<sources>
			<source uri=''/>
		</sources>
	</term> -->

		<term id="Politics">
			<preferredTerm>Politics</preferredTerm>
		</term>

		<term id="Movements">
			<preferredTerm>Movements</preferredTerm>
			<parentTerm term_id="Politics"/>
		</term>

		<term id="Abolitionism">
			<preferredTerm>Abolitionism</preferredTerm>
			<parentTerm term_id="Movements"/>
		</term>

		<term id="Manifest_Destiny">
			<preferredTerm>Manifest Destiny</preferredTerm>
			<parentTerm term_id="Movements"/>
		</term>

		<term id="Nativism">
			<preferredTerm>Nativism</preferredTerm>
			<parentTerm term_id="Movements"/>
		</term>

		<term id="US-Indigenous_Relations">
			<preferredTerm>US-Indigenous Relations</preferredTerm>
			<parentTerm term_id="Politics"/>
		</term>

		<term id="American_Indian_Removal">
			<preferredTerm>American Indian Removal (1830-1847)</preferredTerm>
			<parentTerm term_id="US-Indigenous_Relations"/>
		</term>

		<term id="Indian_Removal_Act_of_1830">
			<preferredTerm>Indian Removal Act of 1830</preferredTerm>
			<parentTerm term_id="American_Indian_Removal"/>
		</term>

		<term id="Treaty_of_Medicine_Creek">
			<preferredTerm>Treaty of Medicine Creek (1854)</preferredTerm>
			<parentTerm term_id="US-Indigenous_Relations"/>
		</term>

		<term id="Medicine_Creek_Treaty_Council">
			<preferredTerm>Medicine Creek Treaty Council</preferredTerm>
			<parentTerm term_id="Treaty_of_Medicine_Creek"/>
		</term>

		<term id="Permanent_Indian_Frontier">
			<preferredTerm>Permanent Indian Frontier (1840)</preferredTerm>
			<parentTerm term_id="US-Indigenous_Relations"/>
		</term>

		<term id="US-Great_Britain_Relations">
			<preferredTerm>US-Great Britain Relations</preferredTerm>
			<parentTerm term_id="Politics"/>
		</term>

		<term id="Oregon_Treaty">
			<preferredTerm>Oregon Treaty (1846)</preferredTerm>
			<parentTerm term_id="US-Great_Britain_Relations"/>
		</term>
	</terms>
</newsletterIndex>
