=== mcm104/uw-capstone-fort-steilacoom/naf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">

    <xs:element name="nameAuthorityFile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agents">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="agent">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="preferredName"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="alternateName"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="family">
                                            <xs:complexType>
                                                <xs:attribute ref="relatedAgent" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="dateOfBirth" minOccurs="0">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:group ref="dates"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="dateOfDeath">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:group ref="dates"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="dateOfMarriage">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:group ref="dates"/>
                                                </xs:choice>
                                                <xs:attribute ref="relatedAgent"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="hasParent">
                                            <xs:complexType>
                                                <xs:attribute ref="relatedAgent" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="hasSpouse">
                                            <xs:complexType>
                                                <xs:attribute ref="relatedAgent" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="tribalAffiliation"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="demographicTerm">
                                            <xs:complexType mixed="true">
                                                <xs:attribute ref="uri" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="sources">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="source">
                                                  <xs:complexType>
                                                  <xs:attribute ref="uri" use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                    <xs:attribute name="agentType" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="person"/>
                                                <xs:enumeration value="family"/>
                                                <xs:enumeration value="corporate body"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="uri" type="xs:anyURI"/>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="relatedAgent" type="xs:IDREF"/>
    <xs:group name="dates">
        <xs:sequence>
            <xs:element minOccurs="0" name="year" type="xs:gYear"/>
            <xs:element minOccurs="0" name="yearMonth" type="xs:gYearMonth"/>
            <xs:element minOccurs="0" name="date" type="xs:date"/>
            <xs:element minOccurs="0" name="approximateDate"/>
            <xs:element minOccurs="0" name="unknown">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:boolean" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== mcm104/uw-capstone-fort-steilacoom/naf_xmltestingDemo.xml
<nameAuthorityFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="naf.xsd">
	<agents>
		<!-- <agent id='' agentType=''>
			<preferredName></preferredName>
			<alternateName/>
			<parentTerm agent=''></parentTerm>
			<relatedTerm agent=''></relatedTerm>
			<scopeNotes/>
			<definition/>
			<sources>
				<source uri=''/>
			</sources>
		</agent> -->

		<agent id="Casey" agentType="family">
			<preferredName>Casey</preferredName>
		</agent>

		<agent id="Silas_Casey_II" agentType="person">
			<preferredName>Silas Casey II</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfBirth>
				<year>1807</year>
			</dateOfBirth>
			<dateOfDeath>
				<year>1882</year>
			</dateOfDeath>
			<dateOfMarriage relatedAgent="Abigail_Abby_Perry_Pearce_Casey">
				<year>1830</year>
			</dateOfMarriage>
			<hasSpouse relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
		</agent>

		<agent id="Abigail_Abby_Perry_Pearce_Casey" agentType="person">
			<preferredName>Abigail "Abby" Perry Pearce Casey</preferredName>
			<alternateName>Abigail Casey</alternateName>
			<alternateName>Abby Casey</alternateName>
			<alternateName>Mrs. Casey</alternateName>
			<family relatedAgent="Casey"/>
			<dateOfMarriage relatedAgent="Silas_Casey_II">
				<year>1830</year>
			</dateOfMarriage>
			<hasSpouse relatedAgent="Silas_Casey_II"/>
			<demographicTerm uri="http://id.loc.gov/authorities/demographicTerms/dg2015060004"
				>Females</demographicTerm>
		</agent>

		<agent id="Abby_Casey" agentType="person">
			<preferredName>Abby Casey</preferredName>
			<alternateName/>
			<family relatedAgent="Casey"/>
			<dateOfMarriage relatedAgent="Lewis_Cass_Hunt">
				<year>1860</year>
			</dateOfMarriage>
			<hasParent relatedAgent="Silas_Casey_II"/>
			<hasParent relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
			<hasSpouse relatedAgent="Lewis_Cass_Hunt"/>
			<demographicTerm uri="http://id.loc.gov/authorities/demographicTerms/dg2015060004"
				>Females</demographicTerm>
		</agent>

		<agent id="Lewis_Cass_Hunt" agentType="person">
			<preferredName>Lewis Cass Hunt</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfMarriage relatedAgent="Abby_Casey">
				<year>1860</year>
			</dateOfMarriage>
			<hasSpouse relatedAgent="Abby_Casey"/>
		</agent>

		<agent id="Edward_Wanton_Casey" agentType="person">
			<preferredName>Edward "Ned" Wanton Casey</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfBirth>
				<year>1850</year>
			</dateOfBirth>
			<dateOfDeath>
				<year>1891</year>
			</dateOfDeath>
			<hasParent relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
			<hasParent relatedAgent="Silas_Casey_II"/>
		</agent>

		<agent id="Elizabeth_Bessie_Casey_Scott" agentType="person">
			<preferredName>Elizabeth "Bessie" Casey Scott</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfBirth>
				<approximateDate>1844</approximateDate>
			</dateOfBirth>
			<hasParent relatedAgent="Silas_Casey_II"/>
			<hasParent relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
			<demographicTerm uri="http://id.loc.gov/authorities/demographicTerms/dg2015060004"
				>Females</demographicTerm>
		</agent>

		<agent id="Thomas_Lincoln_Casey" agentType="person">
			<preferredName>Thomas Lincoln Casey</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfBirth>
				<approximateDate>1832</approximateDate>
			</dateOfBirth>
			<dateOfDeath>
				<year>1896</year>
			</dateOfDeath>
			<hasParent relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
			<hasParent relatedAgent="Silas_Casey_II"/>
			<hasSpouse relatedAgent="Emma_Weir_Casey"/>
		</agent>

		<agent id="Emma_Weir_Casey" agentType="person">
			<preferredName>Emma Weir Casey</preferredName>
			<family relatedAgent="Casey"/>
			<hasSpouse relatedAgent="Thomas_Lincoln_Casey"/>
			<demographicTerm uri="http://id.loc.gov/authorities/demographicTerms/dg2015060004"
				>Females</demographicTerm>
		</agent>

		<agent id="Silas_Casey_III" agentType="person">
			<preferredName>Silas Casey III</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfBirth>
				<year>1841</year>
			</dateOfBirth>
			<dateOfDeath>
				<year>1913</year>
			</dateOfDeath>
			<dateOfMarriage relatedAgent="Sophia_Gray_Herberton_Casey">
				<year>1865</year>
			</dateOfMarriage>
			<hasParent relatedAgent="Abigail_Abby_Perry_Pearce_Casey"/>
			<hasParent relatedAgent="Silas_Casey_II"/>
			<hasSpouse relatedAgent="Sophia_Gray_Herberton_Casey"/>
		</agent>

		<agent id="Sophia_Gray_Herberton_Casey" agentType="person">
			<preferredName>Sophia Gray Herberton Casey</preferredName>
			<family relatedAgent="Casey"/>
			<dateOfMarriage relatedAgent="Silas_Casey_III">
				<year>1865</year>
			</dateOfMarriage>
			<hasSpouse relatedAgent="Silas_Casey_III"/>
			<demographicTerm uri="http://id.loc.gov/authorities/demographicTerms/dg2015060004"
				>Females</demographicTerm>
		</agent>

	</agents>
</nameAuthorityFile>

=== mcm104/uw-capstone-fort-steilacoom/naf_blankXMLfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<nameAuthorityFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="naf.xsd">
    <agents>
        <agent id="" agentType=""> <!-- 1...* --> <!-- id required --> <!-- agentType="person", "family", or "corporate body" -->
            <preferredName></preferredName> <!-- 1...1 -->
            <alternateName></alternateName> <!-- 0...* -->
            <family relatedAgent=""/> <!-- 0...* --> <!-- relatedAgent should only be agent typed as agentType="family" -->
            <dateOfBirth> <!-- 0...1 -->
                <!-- choose ONE of the following elements -->
                <year></year> <!-- YYYY -->
                <!-- OR -->
                <yearMonth></yearMonth> <!-- YYYY-MM -->
                <!-- OR -->
                <date></date> <!-- YYYY-MM-DD -->
                <!-- OR -->
                <approximateDate></approximateDate> <!-- any format, use for uncertain dates -->
                <!-- OR -->
                <unknown value="true"/>
            </dateOfBirth>
            <dateOfDeath> <!-- 0...1 -->
                <!-- same as dateOfBirth -->
            </dateOfDeath>
            <dateOfMarriage relatedAgent=""> <!-- 0...* --> <!-- repeat for every marriage --> <!-- add spouse in relatedAgent if known -->
                <!-- same as dateOfBirth -->
            </dateOfMarriage>
            <hasParent relatedAgent=""/> <!-- 0...* -->
            <hasSpouse relatedAgent=""/> <!-- 0...* -->
            <tribalAffiliation></tribalAffiliation> <!-- 0...* -->
            <demographicTerm uri=""></demographicTerm> <!-- use LCDGT URI in uri, use LCDGT label in element -->
            <sources> <!-- 0...1 -->
                <source uri=""/> <!-- 1...* -->
            </sources>
        </agent>
    </agents>
</nameAuthorityFile>
